# Generated by Django 3.2.6 on 2021-09-16 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("igb", "0003_contract_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_id",
            field=models.CharField(default=uuid.uuid4, max_length=48),
        ),
    ]
