import graphene


class IndustryEnum(graphene.Enum):
    ACADEMIC = "Academic"
    ACCOUNTING = "Accounting"
    ADVERTISING = "Advertising"
    AEROSPACE = "Aerospace"
    AGRICULTURE = "Agriculture"
    ARTS_CULTURE = "Arts & Culture"
    AUTOMOTIVE = "Automotive"
    AVIATION = "Aviation"
    BANKING = "Banking"
    BUILDING_CONSTRUCTION = "Building and Construction"
    CHARITY_AND_NOT_FOR_PROFIT = "Charity and Not for Profit"
    COMMUNICATIONS = "Communications"
    EDUCATION = "Education"
    ENERGY = "Energy"
    ENGINEERING = "Engineering"
    ENTERTAINMENT = "Entertainment"
    FACILITY_MANAGEMENT = "Facility Management"
    FASHION = "Fashion"
    FAST_MOVING_CONSUMER_GOODS = "Fast Moving Consumer Goods"
    FINANCE = "Finance"
    FOOD = "Food"
    GENERIC = "Generic"
    GOVERNMENT_AND_PUBLIC_SECTOR = "Government and Public Sector"
    HEALTH_AND_SAFETY = "Health and Safety"
    HEALTHCARE = "Healthcare"
    HOSPITALITY = "Hospitality"
    INFORMATION_TECHNOLOGY = "Information Technology"
    INSURANCE = "Insurance"
    LANGUAGE = "Language"
    LEGAL = "Legal"
    LEISURE_AND_SPORT = "Leisure and Sport"
    LOGISTICS_SUPPLY_CHAIN = "Logistics & Supply Chain"
    MANUFACTURING = "Manufacturing"
    MARITIME = "Maritime"
    MEDIA = "Media"
    MULTILINGUAL = "Multilingual"
    PHARMACEUTICALS = "Pharmaceuticals"
    PROPERTY_AND_HOUSING = "Property and Housing"
    REAL_ESTATE = "Real Estate"
    RECRUITMENT = "Recruitment"
    RETAIL = "Retail"
    SCIENCE_RESEARCH = "Science & Research"
    SUSTAINABILITY = "Sustainability"
    TELECOMMUNICATIONS = "Telecommunications"
    TRANSPORT_AND_RAIL = "Transport and Rail"
    TRAVEL_AND_TOURISM = "Travel and Tourism"


class SeniorityEnum(graphene.Enum):
    TRAINEE = "Student/Trainee (No experience)"
    GRADUATE = "Entry level/Graduate (0-3 years)"
    MID_OR_SENIOR = "Mid-Senior level (3+ years)"
    MANAGER = "Manager"
    EXECUTIVE = "Executive/Director"


class EducationLeavelEnum(graphene.Enum):
    BACHELOR = "Bachelor / Graduate"
    GCSE = "GCSE / A-Level / Highschool / GED"
    MASTER = "Master / Post-Graduate / PhD"
    VOCATIONAL = "Vocational / Diploma / Associates degree"


class PeriodEnum(graphene.Enum):
    MONTHLY = "Monthly"
    YEARLY = "Yearly"


class EmploymentTypeEnum(graphene.Enum):
    FIXED_TERM = "Fixed term"
    FIXED_TERM_WITH_PERMAMENT = "Fixed term with option for permanent"
    FREELANCE = "Freelance"
    INTERSHIP = "Internship"
    PERMAMENT = "Permanent"
    TRAINEESHIP = "Traineeship"


class CurrenciesEnum(graphene.Enum):
    AFN = "AFN"
    ARS = "ARS"
    AWG = "AWG"
    AUD = "AUD"
    AZN = "AZN"
    BSD = "BSD"
    BBD = "BBD"
    BDT = "BDT"
    BYR = "BYR"
    BZD = "BZD"
    BMD = "BMD"
    BOB = "BOB"
    BAM = "BAM"
    BWP = "BWP"
    BGN = "BGN"
    BRL = "BRL"
    BND = "BND"
    KHR = "KHR"
    CAD = "CAD"
    KYD = "KYD"
    CLP = "CLP"
    CNY = "CNY"
    COP = "COP"
    CRC = "CRC"
    HRK = "HRK"
    CUP = "CUP"
    CZK = "CZK"
    DKK = "DKK"
    DOP = "DOP"
    XCD = "XCD"
    EGP = "EGP"
    SVC = "SVC"
    EEK = "EEK"
    EUR = "EUR"
    FKP = "FKP"
    FJD = "FJD"
    GHC = "GHC"
    GIP = "GIP"
    GTQ = "GTQ"
    GGP = "GGP"
    GYD = "GYD"
    HNL = "HNL"
    HKD = "HKD"
    HUF = "HUF"
    ISK = "ISK"
    INR = "INR"
    IDR = "IDR"
    IRR = "IRR"
    IMP = "IMP"
    ILS = "ILS"
    JMD = "JMD"
    JPY = "JPY"
    JEP = "JEP"
    KZT = "KZT"
    KPW = "KPW"
    KRW = "KRW"
    KGS = "KGS"
    LAK = "LAK"
    LVL = "LVL"
    LBP = "LBP"
    LRD = "LRD"
    LTL = "LTL"
    MKD = "MKD"
    MYR = "MYR"
    MUR = "MUR"
    MXN = "MXN"
    MNT = "MNT"
    MZN = "MZN"
    NAD = "NAD"
    NPR = "NPR"
    ANG = "ANG"
    NZD = "NZD"
    NIO = "NIO"
    NGN = "NGN"
    NOK = "NOK"
    OMR = "OMR"
    PKR = "PKR"
    PAB = "PAB"
    PYG = "PYG"
    PEN = "PEN"
    PHP = "PHP"
    PLN = "PLN"
    QAR = "QAR"
    RON = "RON"
    RUB = "RUB"
    SHP = "SHP"
    SAR = "SAR"
    RSD = "RSD"
    SCR = "SCR"
    SGD = "SGD"
    SBD = "SBD"
    SOS = "SOS"
    ZAR = "ZAR"
    LKR = "LKR"
    SEK = "SEK"
    CHF = "CHF"
    SRD = "SRD"
    SYP = "SYP"
    TWD = "TWD"
    THB = "THB"
    TTD = "TTD"
    TRY = "TRY"
    TRL = "TRL"
    TVD = "TVD"
    UAH = "UAH"
    GBP = "GBP"
    USD = "USD"
    UYU = "UYU"
    UZS = "UZS"
    VEF = "VEF"
    VND = "VND"
    YER = "YER"
    ZWD = "ZWD"
