from algoliasearch_django import AlgoliaIndex
from algoliasearch_django.decorators import register

from api.products.models import JobTitle, Product, JobFunction

from django.conf import settings as django_settings


@register(Product)
class ProductIndex(AlgoliaIndex):
    fields = (
        "id",
        "title",
        "searchable_product_title",
        "url",
        "channel",
        "is_active",
        "is_generic",
        "is_international",
        "duration_days",
        "available_in_ats",
        "salesforce_product_category",
        "similarweb_top_country_shares",
        "customer_id",
        # custom properties
        "channel_type",
        "searchable_industries_ids",
        "searchable_job_functions_ids",
        "searchable_job_titles_ids",
        "searchable_locations_ids",
        "searchable_locations_mapbox_ids",
        "searchable_locations_names",
        "searchable_locations_context_mapbox_ids",
        "primary_similarweb_location",
        "secondary_similarweb_location",
        "maximum_jobfunctions_depth",
        "maximum_locations_cardinality",
        "filterable_status",
        "available_in_jmp",
        "is_addon",
        "is_product",
        "order_frequency",
        "is_my_own_product",
        "searchable_jobfunctions_industries_locations_combinations",
        "searchable_jobfunctions_locations_combinations",
        "searchable_isgeneric_locations_combinations",
        "searchable_isinternational_jobfunctions_combinations",
        "searchable_industries_locations_combinations",
        "searchable_industries_isinternational_combinations",
        "searchable_isgeneric_isinternational",
    )
    settings = {
        "minWordSizefor1Typo": 5,
        "minWordSizefor2Typos": 8,
        "hitsPerPage": 20,
        "maxValuesPerFacet": 100,
        "searchableAttributes": [
            "unordered(searchable_product_title)",
        ],
        "numericAttributesToIndex": [
            "maximum_locations_cardinality",
            "maximum_jobfunctions_depth",
            "duration_days",
        ],
        "attributesToRetrieve": None,
        "ignorePlurals": ["en", "de", "nl"],
        "advancedSyntax": True,
        "unretrievableAttributes": None,
        "optionalWords": None,
        "queryLanguages": ["de", "nl", "en"],
        "attributesForFaceting": [
            "searchable_industries_ids",
            "searchable_job_functions_ids",
            "searchable_job_titles_ids",
            "searchable_locations_ids",
            "searchable_locations_mapbox_ids",
            "searchable_locations_names",
            "searchable_locations_context_mapbox_ids",
            "is_active",
            "is_generic",
            "is_international",
            "filterable_status",
            "available_in_jmp",
            "is_addon",
            "is_product",
            "order_frequency",
            "channel_type",
            "customer_id",
            "is_my_own_product",
            "searchable_jobfunctions_industries_locations_combinations",
            "searchable_jobfunctions_locations_combinations",
            "searchable_isgeneric_locations_combinations",
            "searchable_isinternational_jobfunctions_combinations",
            "searchable_industries_locations_combinations",
            "searchable_industries_isinternational_combinations",
            "searchable_isgeneric_isinternational",
        ],
        "attributesToSnippet": None,
        "attributesToHighlight": None,
        "paginationLimitedTo": 1000,
        "attributeForDistinct": None,
        "exactOnSingleWordQuery": "attribute",
        "ranking": [
            "typo",
            "filters",
            "desc(maximum_locations_cardinality)",
            "desc(maximum_jobfunctions_depth)",
            "desc(order_frequency)",
        ],
        "customRanking": [],
        "separatorsToIndex": "",
        "removeWordsIfNoResults": "lastWords",
        "queryType": "prefixLast",
        "highlightPreTag": "<em>",
        "highlightPostTag": "</em>",
        "snippetEllipsisText": "",
        "alternativesAsExact": ["ignorePlurals", "singleWordSynonym"],
        "indexLanguages": ["en", "nl", "de"],
    }

    index_name = f"{django_settings.ENV}_Product"


@register(JobTitle)
class JobTitleIndex(AlgoliaIndex):
    should_index = "active_and_canonical"
    fields = ("id", "name", "searchable_keywords", "frequency")
    settings = {
        "minWordSizefor1Typo": 5,
        "minWordSizefor2Typos": 8,
        "hitsPerPage": 5,
        "maxValuesPerFacet": 100,
        "minProximity": 10,
        "searchableAttributes": ["unordered(searchable_keywords)"],
        "numericAttributesToIndex": ["maximum_locations_cardinality", "duration_days"],
        "attributesToRetrieve": None,
        "ignorePlurals": ["en", "nl", "de"],
        "decompoundedAttributes": {
            "de": ["searchable_keywords"],
            "nl": ["searchable_keywords"],
        },
        "advancedSyntax": True,
        "unretrievableAttributes": None,
        "optionalWords": None,
        "queryLanguages": ["en", "nl", "de"],
        "attributesForFaceting": ["searchable_keywords"],
        "attributesToSnippet": None,
        "attributesToHighlight": None,
        "paginationLimitedTo": 10,
        "attributeForDistinct": None,
        "exactOnSingleWordQuery": "word",
        "ranking": [
            "typo",
            "exact",
            "words",
            "attribute",
            "proximity",
            "filters",
            "custom",
        ],
        "customRanking": ["desc(frequency)"],
        "separatorsToIndex": "",
        "removeWordsIfNoResults": "allOptional",
        "queryType": "prefixLast",
        "highlightPreTag": "<em>",
        "highlightPostTag": "</em>",
        "snippetEllipsisText": "",
        "alternativesAsExact": ["ignorePlurals", "singleWordSynonym"],
        "indexLanguages": ["en", "nl", "de"],
    }
    index_name = f"{django_settings.ENV}_JobTitle"


@register(JobFunction)
class JobFunctionIndex(AlgoliaIndex):
    fields = ("id", "name", "all_job_titles")
    settings = {
        "minWordSizefor1Typo": 5,
        "minWordSizefor2Typos": 8,
        "hitsPerPage": 5,
        "searchableAttributes": ["unordered(all_job_titles)"],
        "attributesToRetrieve": None,
        "ignorePlurals": ["en", "nl", "de"],
        "decompoundedAttributes": {
            "de": ["all_job_titles"],
            "nl": ["all_job_titles"],
        },
        "advancedSyntax": True,
        "unretrievableAttributes": None,
        "optionalWords": [
            "asia",
            "adviseur",
            "advisor",
            "assistant",
            "associate",
            "consultant",
            "executive",
            "corporate",
            "global",
            "officer",
            "de",
            "e",
            "m",
            "f",
            "x",
            "person",
            "operator",
            "digital",
            "online",
            "ervaran",
            "expert",
            "interim",
            "internship",
            "junior",
            "senior",
            "leader",
            "manager",
            "medeworker",
            "medior",
            "regional",
            "service",
            "specialist",
            "strategisch",
            "supervisor",
            "technisch",
            "teamleider",
            "teammanager",
            "toezichthouder",
            "trainee",
            "jobs",
            "of",
            "werkvoorbereider",
            "general",
            "duties",
            "duty",
            "worker",
            "fulltime",
            "full time",
            "parttime",
            "part time",
        ],
        "queryLanguages": ["en", "nl", "de"],
        "attributesForFaceting": ["all_job_titles"],
        "attributesToSnippet": None,
        "attributesToHighlight": None,
        "paginationLimitedTo": 10,
        "attributeForDistinct": None,
        "exactOnSingleWordQuery": "word",
        "ranking": [
            "typo",
            "exact",
            "words",
            "attribute",
            "proximity",
            "filters",
            "custom",
        ],
        "customRanking": ["desc(frequency)"],
        "separatorsToIndex": "",
        "removeWordsIfNoResults": "allOptional",
        "queryType": "prefixLast",
        "highlightPreTag": "<em>",
        "highlightPostTag": "</em>",
        "snippetEllipsisText": "",
        "alternativesAsExact": ["ignorePlurals", "singleWordSynonym"],
        "indexLanguages": ["en", "nl", "de"],
    }
    index_name = f"{django_settings.ENV}_JobFunction"
