# Generated by Django 3.2.6 on 2021-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("igb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="facets",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
