# Generated by Django 3.2.6 on 2021-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("igb", "0002_contract_facets"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="customer_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
