# Generated by Django 3.2.6 on 2021-09-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("igb", "0004_contract_contract_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="credentials",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contract",
            name="customer_id",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="contract",
            name="facets",
            field=models.JSONField(),
        ),
    ]
