# Generated by Django 3.1.2 on 2020-10-14 09:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='mapbox_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='mapbox_place_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='mapbox_placename',
        ),
        migrations.RemoveField(
            model_name='location',
            name='mapbox_shortcode',
        ),
        migrations.RemoveField(
            model_name='location',
            name='mapbox_text',
        ),
        migrations.RemoveField(
            model_name='location',
            name='mapbox_within',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='geocoder_id',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='place_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='place_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='location',
            name='short_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.URLField(max_length=300, unique=True),
        ),
        migrations.RemoveField(
            model_name='location',
            name='within',
        ),
        migrations.AddField(
            model_name='location',
            name='within',
            field=models.ManyToManyField(to='products.Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
