# Generated by Django 3.1.2 on 2020-10-15 09:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201014_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='desq_country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='desq_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='mapbox_context',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='location',
            name='mapbox_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='mapbox_place_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='mapbox_placename',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='mapbox_shortcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='mapbox_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='mapbox_within',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapbox_location', to='products.location'),
        ),
    ]
