# Generated by Django 3.1.2 on 2020-10-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201015_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_solution',
            new_name='salesforce_product_category',
        ),
        migrations.AddField(
            model_name='location',
            name='canonical_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_in_ats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_in_jmp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='locations', to='products.Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesforce_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
