# Generated by Django 3.1.2 on 2020-10-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201021_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='canonical_name_en',
            new_name='canonical_name',
        ),
    ]
