# Generated by Django 3.1.2 on 2020-10-21 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201021_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mapbox_place_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='industries', related_query_name='industry', to='products.Industry'),
        ),
        migrations.AlterField(
            model_name='product',
            name='job_functions',
            field=models.ManyToManyField(blank=True, related_name='job_functions', related_query_name='job_function', to='products.JobFunction'),
        ),
    ]
