# Generated by Django 3.1.2 on 2020-10-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201027_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='jobFunction',
            new_name='job_function',
        ),
    ]
