# Generated by Django 3.1.2 on 2020-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201029_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapboxlocation',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='similarweb_top_country_shares',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
