# Generated by Django 3.1.3 on 2020-11-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201030_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapboxLocation',
        ),
        migrations.AddField(
            model_name='location',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
