# Generated by Django 3.1.3 on 2020-11-09 17:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_auto_20201110_1010"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="salesforce_industries",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default=list, size=None
            ),
        )
    ]
