# Generated by Django 3.1.3 on 2020-11-12 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_salesforce_cross_postings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_card_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salesforce_job_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='time_to_process',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesforce_industries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None),
        ),
    ]
