# Generated by Django 3.1.3 on 2020-11-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201112_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='duration',
            new_name='duration_days',
        ),
    ]
