# Generated by Django 3.1.3 on 2020-11-17 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201113_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
