# Generated by Django 3.1.3 on 2020-11-17 10:39

from django.db import migrations
import uuid


class Migration(migrations.Migration):

    def set_product_id(apps, schema_editor):
        Product = apps.get_model("products", "Product")
        for row in Product.objects.all():
            product_id = row.desq_product_id if row.desq_product_id else row.salesforce_id
            if not product_id:
                product_id = uuid.uuid4()
            row.product_id = product_id
            row.save(update_fields=['product_id'])

    dependencies = [
        ('products', '0020_product_product_id'),
    ]

    operations = [
        migrations.RunPython(set_product_id, reverse_code=migrations.RunPython.noop),
    ]
