# Generated by Django 3.1.3 on 2020-11-18 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_auto_20201117_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.Location"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            # we forgot to set the field as unique in 0020 :(
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
