# Generated by Django 3.1.3 on 2020-11-19 05:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20201118_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mapbox_place_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('place', 'City, town or village'), ('district', 'Prefecture or county'), ('region', 'State or province'), ('country', 'Country'), ('continent', 'Continent'), ('world', 'International')], max_length=500, null=True), default=list, size=None),
        ),
    ]
