# Generated by Django 3.1.3 on 2020-11-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_jobtitle_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Blacklisted', 'Blacklisted'), ('Disabled', 'Disabled'), ('Negotiated', 'Negotiated'), ('Trial', 'Trial'), (None, '--None--')], default=None, max_length=12, null=True),
        ),
    ]
