# Generated by Django 3.1.3 on 2020-11-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0026_product_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": (
                    ("can_view_product_industries", "Can view product industries"),
                    ("can_change_product_industries", "Can change product industries"),
                    (
                        "can_view_product_job_functions",
                        "Can view product job functions",
                    ),
                    (
                        "can_change_product_job_functions",
                        "Can change product job functions",
                    ),
                )
            },
        ),
    ]
