# Generated by Django 3.1.3 on 2020-11-30 15:00

from django.db import migrations
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    def set_profile(apps, schema_editor):
        Profile = apps.get_model('products', 'Profile')
        User = get_user_model()
        users = User.objects.all()
        for user in users:
            p, created = Profile.objects.get_or_create(user_id=user.id)
            if created:
                p.save()
                user.save()

    dependencies = [
        ('products', '0028_auto_20201201_1342'),
    ]

    operations = [
        migrations.RunPython(set_profile, reverse_code=migrations.RunPython.noop),
    ]
