# Generated by Django 3.1.4 on 2020-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0029_auto_20201201_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="desq_product_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="salesforce_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="salesforce_product_category",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="salesforce_product_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
