# Generated by Django 3.1.4 on 2020-12-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20201203_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='salesforce_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_html_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_method',
            field=models.TextField(choices=[('Fixed duration', 'Fixed duration'), ('Slots', 'Slots'), ('Free', 'Free'), ('Programmatic', 'Programmatic'), ('N/A', 'N/A')], default='Fixed duration'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
