# Generated by Django 3.1.4 on 2020-12-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20201203_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_html_required',
            new_name='has_html_posting',
        ),
        migrations.AlterField(
            model_name='product',
            name='salesforce_product_category',
            field=models.TextField(choices=[('Wallet', 'Wallet'), ('Internal Product', 'Internal Product'), ('Generic Product', 'Generic Product'), ('Customer Specific Product', 'Customer Specific Product'), ('None', '--None--')], default='None', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesforce_product_type',
            field=models.TextField(choices=[('Social', 'Social'), ('Print / Offline', 'Print / Offline'), ('Handling fee', 'Handling fee'), ('Image creation', 'Image creation'), ('Website creation', 'Website creation'), ('VONQ Services/Hours', 'VONQ Services/Hours'), ('Video creation', 'Video creation'), ('Text services', 'Text services'), ('Other', 'Other'), ('Finance', 'Finance'), ('Jobboard', 'Jobboard'), ('Subscription', 'Subscription'), ('Wallet', 'Wallet'), ('Google', 'Google'), ('None', '--None--')], default='None', null=True),
        ),
    ]
