# Generated by Django 3.1.4 on 2020-12-04 12:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20201204_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salesforce_industries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80), default=list, size=None),
        ),
    ]
