# Generated by Django 3.1.4 on 2020-12-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0033_auto_20201204_1202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("jmp", "JMP"),
                    ("mapi", "MAPI"),
                    ("internal", "Internal"),
                ],
                default="internal",
                max_length=15,
            ),
        ),
    ]
