# Generated by Django 3.1.4 on 2020-12-08 10:07

import api.products.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20201207_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='logo_url',
            new_name='salesforce_logo_url',
        ),
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=api.products.models.Product.Logo.logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'svg', 'jpeg']), api.products.models.Product.Logo.validate_logo_size]),
        ),
    ]
