# Generated by Django 3.1.4 on 2020-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20201215_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('job board', 'Job Board'), ('social media', 'Social Media'), ('community', 'Community'), ('publication', 'Publication'), ('aggregator', 'Aggregator'), ('not channel', 'Not Channel')], default='job board', max_length=20),
        ),
    ]
