# Generated by Django 3.1.4 on 2020-12-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0039_channel_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="salesforce_last_sync",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="salesforce_sync_status",
            field=models.CharField(
                choices=[
                    ("synced", "Synced"),
                    ("unsynced", "Unsynced"),
                    ("pending", "Pending"),
                ],
                default="unsynced",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="salesforce_account_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
