# Generated by Django 3.1.4 on 2020-12-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0040_auto_20201203_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="salesforce_last_sync",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="salesforce_sync_status",
            field=models.CharField(
                choices=[
                    ("synced", "Synced"),
                    ("unsynced", "Unsynced"),
                    ("pending", "Pending"),
                ],
                default="unsynced",
                max_length=8,
            ),
        ),
    ]
