# Generated by Django 3.1.5 on 2021-02-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vonqtaxonomy', '0001_initial'),
        ('products', '0045_auto_20210126_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='salesforce_account_id',
            field=models.CharField(max_length=20, null=True, verbose_name='Salesforce Account'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='vonq_taxonomy_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vonqtaxonomy.industry'),
        ),
        migrations.AlterField(
            model_name='jobfunction',
            name='vonq_taxonomy_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vonqtaxonomy.jobcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_to_process',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time to process (hours)'),
        ),
    ]
