# Generated by Django 3.1.6 on 2021-02-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20210203_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_my_own_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_method',
            field=models.CharField(choices=[('Portfolio DE', 'Portfolio DE'), ('Portfolio INT', 'Portfolio INT'), ('Portfolio NL', 'Portfolio NL'), ('Portfolio UK', 'Portfolio UK'), ('Portfolio US', 'Portfolio US'), ('Premium DE', 'Premium DE'), ('Premium INT', 'Premium INT'), ('Portfolio FR', 'Portfolio FR'), ('Premium NL', 'Premium NL'), ('Premium UK', 'Premium UK'), ('Premium FR', 'Premium FR'), ('Premium US', 'Premium US'), ('Tropical DE', 'Tropical DE'), ('Tropical INT', 'Tropical INT'), ('Tropical NL', 'Tropical NL'), ('Tropical UK', 'Tropical UK'), ('Additional', 'Additional'), ('Indeed Always On', 'Indeed Always On'), ('TraffiQ / SEA (VONQ Team)', 'TraffiQ / SEA (VONQ Team)'), ('TraffiQ / SEA (Expand Online)', 'TraffiQ / SEA (Expand Online)'), ('Project Management (e.g. hours)', 'Project Management (e.g. hours)'), ('Addon: financial', 'Addon: financial'), ('Internal / Tracking / Technical', 'Internal / Tracking / Technical'), ('Kickbacks', 'Kickbacks'), ('Subscription', 'Subscription'), ('None', '--None--')], default='None', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price_method',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable'), ('None', '--None--')], default='None', max_length=10, null=True),
        ),
    ]
