# Generated by Django 3.1.6 on 2021-02-17 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0048_auto_20210209_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="mapbox_bounding_box",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=list, size=None
            ),
        ),
    ]
