# Generated by Django 3.1.6 on 2021-02-18 15:50

import api.products.models
from django.db import migrations, models
import image_cropping.fields
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_location_mapbox_bounding_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cropping_rectangle',
            field=image_cropping.fields.ImageRatioField('logo', '270x90', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping rectangle'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping_square',
            field=image_cropping.fields.ImageRatioField('logo', '68x68', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping square'),
        ),
        migrations.AddField(
            model_name='product',
            name='logo_rectangle',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=api.products.models.Product.Logo.logo_path),
        ),
        migrations.AddField(
            model_name='product',
            name='logo_square',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=api.products.models.Product.Logo.logo_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, help_text='Rules: Logo size must be 1MB max. Logo file must be an image.', null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=api.products.models.Product.Logo.logo_path, validators=[api.products.models.Product.Logo.validate_logo_size]),
        ),
    ]
