# Generated by Django 3.1.6 on 2021-02-22 11:24

import datetime

import pytz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0050_auto_20210218_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="created",
            # Set default created field at epoch 0 to easily point entities that have been created
            # before the fields have been introduced.
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=pytz.UTC),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="location",
            name="created",
            # Set default created field at epoch 0 to easily point entities that have been created
            # before the fields have been introduced.
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=pytz.UTC),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created",
            # Set default created field at epoch 0 to easily point entities that have been created
            # before the fields have been introduced.
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=pytz.UTC),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="created",
            # Set default created field at epoch 0 to easily point entities that have been created
            # before the fields have been introduced.
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=pytz.UTC),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
