# Generated by Django 3.1.7 on 2021-03-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20210308_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text='\nChannel with one product: Stepstone\n<br/>\nChannel with multiple products: Stepstone - Premium Ad\n<br/>\nChannel with multiple countries: Stepstone | Germany\n<br/>\nChannel with multiple countries & products: Stepstone | Germany - Premium Ad\n<br/>\nChannel with extra product features: Stepstone - Premium Ad + Newsletter\n<br/>\nChannel with target group segmentation: Indeed - Sales', max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name_de',
            field=models.CharField(help_text='\nChannel with one product: Stepstone\n<br/>\nChannel with multiple products: Stepstone - Premium Ad\n<br/>\nChannel with multiple countries: Stepstone | Germany\n<br/>\nChannel with multiple countries & products: Stepstone | Germany - Premium Ad\n<br/>\nChannel with extra product features: Stepstone - Premium Ad + Newsletter\n<br/>\nChannel with target group segmentation: Indeed - Sales', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name_en',
            field=models.CharField(help_text='\nChannel with one product: Stepstone\n<br/>\nChannel with multiple products: Stepstone - Premium Ad\n<br/>\nChannel with multiple countries: Stepstone | Germany\n<br/>\nChannel with multiple countries & products: Stepstone | Germany - Premium Ad\n<br/>\nChannel with extra product features: Stepstone - Premium Ad + Newsletter\n<br/>\nChannel with target group segmentation: Indeed - Sales', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name_nl',
            field=models.CharField(help_text='\nChannel with one product: Stepstone\n<br/>\nChannel with multiple products: Stepstone - Premium Ad\n<br/>\nChannel with multiple countries: Stepstone | Germany\n<br/>\nChannel with multiple countries & products: Stepstone | Germany - Premium Ad\n<br/>\nChannel with extra product features: Stepstone - Premium Ad + Newsletter\n<br/>\nChannel with target group segmentation: Indeed - Sales', max_length=200, null=True),
        ),
    ]
