# Generated by Django 3.1.7 on 2021-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_auto_20210310_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate_card_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Rate Card URL'),
        ),
    ]
