# Generated by Django 3.1.7 on 2021-03-12 11:02

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_product_rate_card_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cross_postings',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='mapbox_bounding_box',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='mapbox_context',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='mapbox_place_type',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('place', 'City, town or village'), ('district', 'Prefecture or county'), ('region', 'State or province'), ('country', 'Country'), ('continent', 'Continent'), ('world', 'International')], max_length=500, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesforce_industries',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesforce_job_categories',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None),
        ),
    ]
