# Generated by Django 3.1.7 on 2021-03-15 13:05

import api.products.models
from django.db import migrations, models
import image_cropping.fields
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_remove_product_salesforce_cross_postings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='logo',
            new_name='logo_rectangle_uncropped',
        ),
        migrations.AddField(
            model_name='product',
            name='logo_square_uncropped',
            field=models.ImageField(blank=True, help_text="Rules: Logo size must be 1MB max. Main supported formats: ['bmp', 'gif', 'png', 'jpg', 'jpeg']", null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=api.products.models.Product.Logo.logo_path, validators=[api.products.models.Product.Logo.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_rectangle',
            field=image_cropping.fields.ImageRatioField('logo_rectangle_uncropped', '270x90', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping rectangle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_square',
            field=image_cropping.fields.ImageRatioField('logo_square_uncropped', '68x68', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping square'),
        ),
    ]
