# Generated by Django 3.1.7 on 2021-03-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_auto_20210315_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ra_click_frequency',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
