# Generated by Django 3.1.7 on 2021-03-25 12:19

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0061_product_ra_click_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cross_postings",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="This field should only contain URLs (ex. www.facebook.com)",
                null=True,
                size=None,
            ),
        ),
    ]
