# Generated by Django 3.2 on 2021-04-19 16:05

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_is_active_field(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    active_products = Product.objects.filter(is_active=True, status__isnull=True)
    updated = active_products.update(status="Active")
    logger.info(f"Migrated {updated} products to 'Active' status")

    disabled_products = Product.objects.filter(status__in=["Disabled", "Blacklisted"])
    updated = disabled_products.update(available_in_jmp=False, is_recommended=False)
    logger.info(
        f"Migrated {updated} products to 'Available in JMP = False' and 'Is Recommended = False'"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0067_alter_product_status"),
    ]

    operations = [
        migrations.RunPython(
            migrate_is_active_field, reverse_code=migrations.RunPython.noop
        ),
    ]
