# Generated by Django 3.2 on 2021-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0068_auto_20210419_1605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Blacklisted", "Blacklisted"),
                    ("Disabled", "Disabled"),
                    ("Active", "Active"),
                ],
                default=None,
                max_length=12,
                null=True,
            ),
        ),
    ]
