# Generated by Django 3.2 on 2021-04-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0069_alter_product_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
    ]
