# Generated by Django 3.2 on 2021-04-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0070_remove_product_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Product Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_de",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Product Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Product Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title_nl",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Product Name"
            ),
        ),
    ]
