# Generated by Django 3.1.7 on 2021-05-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_category_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products_pkb_product',
        ),
    ]
