# Generated by Django 3.2 on 2021-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0073_rename_time_to_process_product_supplier_time_to_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vonq_time_to_process",
            field=models.IntegerField(
                default=24, null=True, verbose_name="VONQ time to process (hours)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier_time_to_process",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Supplier time to process (hours)"
            ),
        ),
    ]
