# Generated by Django 3.2 on 2021-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_alter_product_supplier_time_to_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_time_to_process',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Supplier time to process (hours)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vonq_time_to_process',
            field=models.PositiveIntegerField(default=24, null=True, verbose_name='VONQ time to process (hours)'),
        ),
    ]
