# Generated by Django 3.2 on 2021-04-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_auto_20210428_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_setup_time',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Supplier setup time (hours)'),
        ),
    ]
