# Generated by Django 3.2 on 2021-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0077_product_supplier_setup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vonq_time_to_process',
            field=models.IntegerField(default=24, null=True, verbose_name='VONQ time to process (hours)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='products_pr_created_1360ea_idx'),
        ),
    ]
