# Generated by Django 3.2.4 on 2021-06-14 09:31

import api.arrayfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0079_alter_product_supplier_time_to_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cross_postings",
            field=api.arrayfield.PKBArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="This field should only contain URLs (ex. www.facebook.com)",
                null=True,
                size=None,
            ),
        ),
    ]
