# Generated by Django 3.2 on 2021-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_auto_20210509_2047'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pk_created_4dbf65_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='products_pr_created_1360ea_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
