# Generated by Django 3.2.4 on 2021-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0080_alter_product_cross_postings"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="remarks",
            field=models.CharField(
                choices=[
                    ("Product no longer exists", "Product no longer exists"),
                    (
                        "Product is temporarily offline due to a contract negotiation",
                        "Product is temporarily offline due to a contract negotiation",
                    ),
                    (
                        "Product doesn’t allow posting under your employer name",
                        "Product doesn’t allow posting under your employer name",
                    ),
                    (
                        "Product doesn’t meet delivery time criteria",
                        "Product doesn’t meet delivery time criteria",
                    ),
                    (
                        "Product doesn’t want to be part of the market place",
                        "Product doesn’t want to be part of the market place",
                    ),
                    ("None", "--None--"),
                ],
                default=None,
                max_length=64,
                null=True,
            ),
        ),
    ]
