# Generated by Django 3.1.5 on 2021-01-13 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_auto_20201222_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerate",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
