# industries and job categories codelists in igb
igb_industries = {
    "Administratief / call center": True,
    "Adviesbureau / Consultancy": True,
    "Agrarisch / Visserij": True,
    "Amusement": True,
    "Arbeidsbemiddeling": True,
    "Arbeidsbemiddeling / W&S / Uitzenden / Detachering": True,
    "Automatisering / ICT": True,
    "Automotive": True,
    "Bank & Verzekeringswezen": True,
    "Beveiliging / Brandweer / Politie": True,
    "Biotechnologie": True,
    "Bouw": True,
    "Chemische": True,
    "Cultuur / Kunst": True,
    "Cultuur / Recreatie": True,
    "Defensie / Politie / Brandweer": True,
    "Detailhandel / Groothandel": True,
    "Drukkerij / Grafimedia": True,
    "E-commerce": True,
    "Elektronica": True,
    "Energie & Nutsvoorziening": True,
    "Facilitaire dienstverlening (Beveiliging / Schoonmaak)": True,
    "Facilitiair / Schoonmaak": True,
    "Farmaceutisch": True,
    "Fast Moving Consumer Goods": True,
    "Financieel / Verzekeringen": True,
    "Financiele dienstverlening": True,
    "Gezondheidszorg / Welzijn": True,
    "Handel": True,
    "Horeca": True,
    "Horeca / Recreatie / Reizen": True,
    "ICT": True,
    "Industrie / Techniek": True,
    "Juridisch": True,
    "Landbouw / Bosbouw / Visserij": True,
    "Logistiek": True,
    "Luchtvaart / Ruimtevaart": True,
    "Maakindustrie": True,
    "Machines en installatiebouw": True,
    "Maritiem": True,
    "Media / Communicatie": True,
    "Medisch / Zorg / Welzijn": True,
    "Mode": True,
    "Nutsvoorzieningen": True,
    "Olie en Gas": True,
    "Onderwijs / Onderzoek": True,
    "Onderwijs / Opleiding": True,
    "Overheid / Non-profit": True,
    "Overig": True,
    "Persoonlijke dienstverlening": True,
    "Pharma / Chemie": True,
    "Reclame / Communicatie / Media": True,
    "Sport": True,
    "Techniek": True,
    "Telecommunicatie": True,
    "Transport / Logistiek": True,
    "Voedingsmiddelenindustrie": True,
    "Woningcorporaties / Projectontwikkelaars / Vastgoed": True,
    "Zakelijke dienstverlening": True,
    "Zware Industrie": True,
}

igb_job_categories = {
    "Accountancy / Controlling / Fiscaal": True,
    "Administratie en klantenservice": True,
    "Administratie: Data entry": True,
    "Administratie: Financieel": True,
    "Advies / Consultancy": True,
    "Bank & Verzekeringen": True,
    "Beleid en bestuur": True,
    "Beveiliging": True,
    "Bouw - Architectuur": True,
    "Bouw - Engineering": True,
    "Bouw - Uitvoerend": True,
    "Bouw - Werkvoorbereiding": True,
    "Bouw en delfstoffenwinning": True,
    "Chemical Engineering": True,
    "Commercieel - Account Management": True,
    "Commercieel - Binnendienst / Telesales / Callcenter": True,
    "Commercieel - Business Development": True,
    "Commercieel - Detailhandel": True,
    "Commercieel - Ondersteunend / Support / Helpdesk": True,
    "Communicatie / PR": True,
    "Communicatie, marketing en PR": True,
    "Defensie": True,
    "Dieren (Medisch en Verzorging)": True,
    "Directie / Management / Bestuur": True,
    "E-Commerce / Search Engine Marketing & Optimisation": True,
    "Embedded Software": True,
    "Engineering": True,
    "Facilitair Beheer": True,
    "Farmacie": True,
    "Financieel economisch / Bedrijfskundig / Financieel Management": True,
    "Gezondheidszorg en welzijn": True,
    "Goede doelen / Fondsenwerving": True,
    "Grafisch (Drukkerij)": True,
    "Grafisch (Ontwerp / Vormgeving / DTP)": True,
    "Horeca": True,
    "Horeca / Toerisme / Recreatie": True,
    "ICT - Hardware / Netwerk": True,
    "ICT - Services & Support": True,
    "ICT - Software ontwikkeling": True,
    "Informatie- en communicatietechnologie": True,
    "Inkoop en magazijnbeheer": True,
    "Installatie, reparatie en onderhoud": True,
    "Journalistiek / Redactie / Copywriting": True,
    "Juridisch": True,
    "Kunst en Cultuur": True,
    "Kunst, cultuur en media": True,
    "Kwaliteit / Arbo / Milieu / Veiligheid": True,
    "Laboratorium": True,
    "Landbouw / Tuinbouw / Visserij": True,
    "Landbouw, veeteelt en visserij": True,
    "Logistiek: Inkoop & Supply Chain": True,
    "Logistiek: Voorraadbeheer, Magazijn en Chauffeurs": True,
    "Maatschappelijk werk": True,
    "Makelaardij": True,
    "Maritiem": True,
    "Marketing": True,
    "Mode / Styling / Cosmetica": True,
    "Natuur- en milieuwetenschappen": True,
    "Onderwijs / Coaching / Trainers": True,
    "Onderwijs, opleiding en training": True,
    "Personeel & Organisatie / HRM": True,
    "Persoonlijke dienstverlening": True,
    "Piloot": True,
    "Planologie / Ruimtelijke ordening": True,
    "Politie, brandweer en beveiliging": True,
    "Politiek / Beleid": True,
    "Productie": True,
    "Productie (Operators)": True,
    "Projectmanagement": True,
    "Radio & Televisie": True,
    "Recht, arbeid en maatschappij": True,
    "Recreatie, sport en toerisme": True,
    "Recruitment / Arbeidsbemiddeling": True,
    "Salarisadministratie": True,
    "Schoonmaak / Interieurverzorging": True,
    "Schoonmaak en beheer": True,
    "Secretarieel / Office Management / Personal Assistant": True,
    "Sport": True,
    "Techniek - Engineering": True,
    "Techniek - Ontwerp / design": True,
    "Techniek - Uitvoerend": True,
    "Techniek - Werkvoorbereiding (Berekening/Planning)": True,
    "Verkoop en handel": True,
    "Vervoer en transport": True,
    "Verzekeringen en financiën": True,
    "Volkshuisvesting": True,
    "Wetenschap, Research & Development": True,
    "Zorg - Artsen / Chirurgen": True,
    "Zorg - Geestelijke gezondheidszorg": True,
    "Zorg - Kinderen (dagverblijf)": True,
    "Zorg - Lichamelijke gezondheidszorg": True,
}
