# Generated by Django 3.1.7 on 2021-03-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20210326_1101'),
        ('order', '0101_auto_20210308_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campaign.campaign'),
        ),
    ]
