# Generated by Django 3.1.2 on 2020-10-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201015_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='geocoder_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='short_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='text',
        ),
        migrations.RemoveField(
            model_name='location',
            name='within',
        ),
    ]
