# Generated by Django 3.1.2 on 2020-10-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201015_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='locations', to='products.Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesforce_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
