# Generated by Django 3.1.2 on 2020-10-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201021_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapboxLocation',
            fields=[
                ('mapbox_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mapbox_data', models.JSONField()),
            ],
        ),
    ]
