# Generated by Django 3.1.2 on 2020-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_auto_20201104_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="salesforce_product_category",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
