# Generated by Django 3.1.4 on 2020-12-09 11:41

import api.products.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20201208_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.FileField(blank=True, help_text='Rules: Logo size must be 1MB max. Logo file must be an image.', null=True, upload_to=api.products.models.Product.Logo.logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'svg', 'jpeg']), api.products.models.Product.Logo.validate_logo_size]),
        ),
    ]
