# Generated by Django 3.1.5 on 2021-01-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_treejobfunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_requirement_type', models.TextField(choices=[('Location', 'Location'), ('Salary Indication', 'Salary Indication'), ('Career Level', 'Career level'), ('Language Specific', 'Language Specific'), ('Contact Information', 'Contact Information'), ('Company Registration Information', 'Company Registration Information'), ('Facebook Profile', 'Facebook Profile'), ('LinkedIn Profile', 'LinkedIn Profile'), ('Xing Profile', 'Xing Profile'), ('Hours', 'Hours'), ('None', '--None--')], default='None', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobfunction',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='job_functions',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.JobFunction'),
        ),
        migrations.AddField(
            model_name='product',
            name='posting_requirements',
            field=models.ManyToManyField(blank=True, related_name='posting_requirements', related_query_name='posting_requirement', to='products.PostingRequirement'),
        ),
    ]
