# Generated by Django 3.1.5 on 2021-01-26 18:10
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


def run_import_taxonomy_command(*args, **kwargs):
    call_command("import_vonq_taxonomy_mappings"),


class Migration(migrations.Migration):

    dependencies = [
        ('vonqtaxonomy', '0001_initial'),
        ('products', '0044_auto_20210127_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='vonq_taxonomy_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vonqtaxonomy.industry'),
        ),
        migrations.AddField(
            model_name='jobfunction',
            name='vonq_taxonomy_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vonqtaxonomy.jobcategory'),
        ),
        migrations.RunPython(
            run_import_taxonomy_command,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
