# Generated by Django 3.1.7 on 2021-03-08 15:01

import api.products.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20210301_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.URLField(max_length=300, verbose_name='Channel URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, help_text="Rules: Logo size must be 1MB max. Main supported formats: ['bmp', 'gif', 'png', 'jpg', 'jpeg']", null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=api.products.models.Product.Logo.logo_path, validators=[api.products.models.Product.Logo.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Purchase Price (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate_card_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate Card Price (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Unit Price (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Product URL'),
        ),
    ]
