# Generated by Django 3.2 on 2021-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0064_auto_20210408_1114"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="has_html_posting",
        )
    ]
