# Generated by Django 3.1.7 on 2021-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_auto_20210421_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('career level', 'Career level'), ('diversity', 'Diversity'), ('job type', 'Job type'), ('industry', 'Industry')], max_length=50, null=True),
        ),
    ]
