# Generated by Django 3.2.4 on 2021-06-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0081_disabled_product_reason"),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=migrations.RunPython.noop
        )
    ]
