# Generated by Django 3.2.4 on 2021-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0082_populate_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Product no longer exists", "Product no longer exists"),
                    (
                        "Product is temporarily offline due to a contract negotiation",
                        "Product is temporarily offline due to a contract negotiation",
                    ),
                    (
                        "Product doesn’t allow posting under your employer name",
                        "Product doesn’t allow posting under your employer name",
                    ),
                    (
                        "Product doesn’t meet delivery time criteria",
                        "Product doesn’t meet delivery time criteria",
                    ),
                    (
                        "Product doesn’t want to be part of the market place",
                        "Product doesn’t want to be part of the market place",
                    ),
                    ("None", "--None--"),
                ],
                default="None",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="remarks",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
