# Generated by Django 3.2.4 on 2021-06-29 10:06
import logging
from django.db import migrations
from django.db.models import Model, Q
from django.db.models.functions import Length
from django.utils.text import Truncator


logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    def truncate_long_channel_names(apps, schema_editor):
        """
        Before we can alter the schema we'll need to truncate the
        existing long channel names
        """
        Channel = apps.get_model("products", "Channel")  # type: Model

        channels_with_long_names = Channel.objects.annotate(
            name_len=Length("name"),
            name_en_len=Length("name_en"),
            name_de_len=Length("name_de"),
            name_nl_len=Length("name_nl"),
        ).filter(
            Q(name_len__gt=80)
            | Q(name_en_len__gt=80)
            | Q(name_de_len__gt=80)
            | Q(name_nl_len__gt=80)
        )
        if channels_with_long_names.count() > 0:
            logger.debug(
                f"Found {channels_with_long_names.count()} problematic channels, migrating"
            )
            for channel in channels_with_long_names:
                channel.name = Truncator(channel.name).chars(79)
                channel.name_en = Truncator(channel.name_en).chars(79)
                channel.name_nl = Truncator(channel.name_nl).chars(79)
                channel.name_de = Truncator(channel.name_de).chars(79)
                channel.save()

    dependencies = [
        ("products", "0086_populate_remarks_for_active_products"),
    ]

    operations = [
        migrations.RunPython(
            truncate_long_channel_names, reverse_code=migrations.RunPython.noop
        ),
    ]
