# Generated by Django 3.2.4 on 2021-06-29 10:06
import logging
from django.db import migrations
from django.db.models import Model
from django.db.models.functions import Length
from django.utils.text import Truncator


logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    def truncate_long_channel_names(apps, schema_editor):
        """
        Before we can alter the schema we'll need to truncate the
        existing long channel names
        """
        Channel = apps.get_model("products", "Channel")  # type: Model

        channels_with_long_names = Channel.objects.annotate(
            name_len=Length("name")
        ).filter(name_len__gt=80)
        if channels_with_long_names.count() > 0:
            logger.debug(
                f"Found {channels_with_long_names.count()} problematic channels, migrating"
            )
            for channel in channels_with_long_names:
                truncated_channel_name = Truncator(channel.name).chars(80)
                logger.info(f"Truncating {channel.name} to {truncated_channel_name}")
                channel.name = Truncator(channel.name).chars(80)
                channel.save()

    dependencies = [
        ("products", "0086_populate_remarks_for_active_products"),
    ]

    operations = [
        migrations.RunPython(
            truncate_long_channel_names, reverse_code=migrations.RunPython.noop
        ),
    ]
