# Generated by Django 3.2.4 on 2021-06-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0088_auto_20210629_1027"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="mapbox_placename_de",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="mapbox_placename_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="mapbox_placename_nl",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="mapbox_text_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="mapbox_text_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="mapbox_text_nl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
