# Generated by Django 3.2.5 on 2021-07-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0089_auto_20210630_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
