# Generated by Django 3.2.6 on 2021-08-05 10:21
import logging

from django.db import migrations, models
logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    def not_channel_to_service(apps, schema_editor):
        """
        Simple data migration
        """
        Channel = apps.get_model("products", "Channel")  # type: Model

        not_a_channel_channels = Channel.objects.filter(
            type='not channel'
        )
        logger.debug(
            f"Migrating {not_a_channel_channels.count()} non-channels to services."
        )
        not_a_channel_channels.update(type='service')

    def service_to_not_channel(apps, schema_editor):
        """
        Simple data migration reversion
        """
        Channel = apps.get_model("products", "Channel")  # type: Model

        service_channels = Channel.objects.filter(
            type='service'
        )
        logger.debug(
            f"Reverting {service_channels.count()} services to non-channels."
        )
        service_channels.update(type='not channel')

    dependencies = [
        ('products', '0090_alter_product_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('job board', 'Job Board'), ('social media', 'Social Media'), ('community', 'Community'), ('publication', 'Publication'), ('aggregator', 'Aggregator'), ('service', 'Service')], default='job board', max_length=20),
        ),
        migrations.RunPython(
            not_channel_to_service, reverse_code=service_to_not_channel
        ),
    ]
