# Generated by Django 3.2.6 on 2021-09-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0092_auto_20210920_1054"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="igb_moc_channel_class",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="igb_moc_extended_information",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
