# Generated by Django 3.2.6 on 2021-09-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0093_auto_20210908_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="moc_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="moc_only",
            field=models.BooleanField(default=False),
        ),
    ]
