# Generated by Django 3.2.8 on 2021-10-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0094_auto_20210913_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="igb_facets",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
